const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('easyaiDesktop', {
  pickFile: () => ipcRenderer.invoke('easyai:pick-file'),
  pickProjectDirectory: () => ipcRenderer.invoke('easyai:pick-project-directory'),
  createProjectWorkspace: (value) => ipcRenderer.invoke('easyai:create-project-workspace', value),
  listProjectFiles: (root) => ipcRenderer.invoke('easyai:list-project-files', root),
  readProjectFile: (root, relative) => ipcRenderer.invoke('easyai:read-project-file', root, relative),
  writeProjectFile: (root, relative, content) => ipcRenderer.invoke('easyai:write-project-file', root, relative, content),
  syncProjectWorkspace: (root, runId) => ipcRenderer.invoke('easyai:sync-project-workspace', root, runId),
  materializeProjectAssets: (root, assetIds) => ipcRenderer.invoke('easyai:materialize-project-assets', root, assetIds),
  registerPreviewRoot: (root) => ipcRenderer.invoke('easyai:register-preview-root', root),
  registerAssetPreviewRoot: (assetId) => ipcRenderer.invoke('easyai:register-asset-preview-root', assetId),
  readProjectPreview: (root, relative) => ipcRenderer.invoke('easyai:read-project-preview', root, relative),
  readAssetPreview: (assetId) => ipcRenderer.invoke('easyai:read-asset-preview', assetId),
  revealProjectFile: (root, relative) => ipcRenderer.invoke('easyai:reveal-project-file', root, relative),
  openAssetInBrowser: (assetId) => ipcRenderer.invoke('easyai:open-asset-in-browser', assetId),
  openProjectFileInBrowser: (root, relative) => ipcRenderer.invoke('easyai:open-project-file-in-browser', root, relative),
  pickSkill: () => ipcRenderer.invoke('easyai:pick-skill'),
  createSkill: (skill) => ipcRenderer.invoke('easyai:create-skill', skill),
  writeSkillDraft: (draft) => ipcRenderer.invoke('easyai:write-skill-draft', draft),
  readSkillDraft: (path) => ipcRenderer.invoke('easyai:read-skill-draft', path),
  listSkillFiles: (path) => ipcRenderer.invoke('easyai:list-skill-files', path),
  readSkillFile: (path) => ipcRenderer.invoke('easyai:read-skill-file', path),
  writeSkillFile: (path, content) => ipcRenderer.invoke('easyai:write-skill-file', path, content),
  deleteManagedSkill: (path) => ipcRenderer.invoke('easyai:delete-managed-skill', path),
  installSkill: (reference) => ipcRenderer.invoke('easyai:install-skill', reference),
  importGitSkill: (url) => ipcRenderer.invoke('easyai:import-git-skill', url),
  findSkills: (query, batchCount) => ipcRenderer.invoke('easyai:find-skills', query, batchCount),
  openExternal: (url) => ipcRenderer.invoke('easyai:open-external', url),
  getModelConfig: () => ipcRenderer.invoke('easyai:get-model-config'),
  saveModelConfig: (config) => ipcRenderer.invoke('easyai:save-model-config', config),
  getSearchConfig: () => ipcRenderer.invoke('easyai:get-search-config'),
  saveSearchConfig: (config) => ipcRenderer.invoke('easyai:save-search-config', config),
  testProvider: (value) => ipcRenderer.invoke('easyai:test-provider', value),
  listProviderModels: (value) => ipcRenderer.invoke('easyai:list-provider-models', value),
  listOllamaModels: (baseUrl) => ipcRenderer.invoke('easyai:list-ollama-models', baseUrl),
  pullOllamaModel: (baseUrl, modelName) => ipcRenderer.invoke('easyai:pull-ollama-model', baseUrl, modelName),
  storageGet: (key) => ipcRenderer.invoke('easyai:storage-get', key),
  storageSet: (key, value) => ipcRenderer.invoke('easyai:storage-set', key, value),
  listAssets: () => ipcRenderer.invoke('easyai:list-assets'),
  archiveArtifact: (artifact) => ipcRenderer.invoke('easyai:archive-artifact', artifact),
  linkAssetsToProject: (value) => ipcRenderer.invoke('easyai:link-assets-to-project', value),
  unlinkAssetsFromProject: (assetIds) => ipcRenderer.invoke('easyai:unlink-assets-from-project', assetIds),
  saveAsset: (assetId) => ipcRenderer.invoke('easyai:save-asset', assetId),
  revealAsset: (assetId) => ipcRenderer.invoke('easyai:reveal-asset', assetId),
  getChannelSettings: () => ipcRenderer.invoke('easyai:get-channel-settings'),
  saveChannelSettings: (payload) => ipcRenderer.invoke('easyai:save-channel-settings', payload),
  gatewayStatus: () => ipcRenderer.invoke('easyai:gateway-status'),
  gatewayRestart: () => ipcRenderer.invoke('easyai:gateway-restart'),
  checkEnvironment: () => ipcRenderer.invoke('easyai:env-check'),
  onEnvCheckProgress: (callback) => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('easyai:env-check-progress', listener);
    return () => ipcRenderer.removeListener('easyai:env-check-progress', listener);
  },
});
